### ISSUE TITLE
nobs.plm

### ISSUE THREAD

**Issue by helix123** [jepusto/clubSandwich#13]
I noticed there is a `nobs.plm` function in this package. This makes sense because the current CRAN release of `plm` does not have this method. Since some time, it is implementend in the development version of plm (https://r-forge.r-project.org/projects/plm/).

Just a tiny note about clubSandwich's implementation: 

```
 nobs.plm <- function(object, ...) {
   NROW(object$model)
 }
```

This should work for FE and RE models. For FD models, the original/undifferenced data is kept in `object$model`, thus this will likely yield a somewhat wrong number. However, I don't know if FD models are supported by clubSandwich. I recommend to use `length(object$residuals)` which will give the number of (differenced) observations used in the (FD) model estimation and does the trick for FE and RE models as well. This is likely the number we want here?

**Comment by jepusto** [comment]
Thanks for the pointer. I've modified the nobs.plm method as you suggested, and also made a few other tweaks so that clubSandwich works on FD models. Here's a chunk of the unit tests:

```
library(testthat)
library(plm)
devtools::load_all()
data(Fatalities, package = "AER")
Fatalities <- within(Fatalities, {
  frate <- 10000 * fatal / pop
  drinkagec <- cut(drinkage, breaks = 18:22, include.lowest = TRUE, right = FALSE)
  drinkagec <- relevel(drinkagec, ref = 4)
})

plm_FD <- plm(frate ~ beertax + drinkagec + miles + unemp + log(income),
              data = Fatalities, index = c("state", "year"), 
              model = "fd")

expect_equal(vcovHC(plm_FD, method="arellano", type = "HC0", cluster = "group"), 
               as.matrix(vcovCR(plm_FD, type = "CR0")))
expect_equal(vcovHC(plm_FD, method="arellano", type = "sss", cluster = "group"), 
               as.matrix(vcovCR(plm_FD, type = "CR1S")))
```

However, when I try to cluster on time-point clubSandwich does not agree with vcovHC.plm:
```
expect_equal(vcovHC(plm_FD, method="arellano", type = "HC0", cluster = "time"), 
               as.matrix(vcovCR(plm_FD, cluster = "time", type = "CR0")))
expect_equal(vcovHC(plm_FD, method="arellano", type = "sss", cluster = "time"), 
               as.matrix(vcovCR(plm_FD, cluster = "time", type = "CR1S")))
```
I'm not sure why that would be. Any intuition?

**Comment by helix123** [comment]
Mh, just a guess without looking at the respective codes: for FD models we loose one time period. Maybe either `vcovHC.plm` or `vcovRC` does not account for that loss when clustering on time?

**Comment by helix123** [comment]
I had a glimpse at plm's vcovG.R and they have some adjustment for FD models (search for "fix for 'fd' model (losing first time period)")). Not sure if clubSandwich's or plm's implementation is right here.
In any case, `attr(model.frame(plm_FD), "index"` will give you the original index, i.e. all time periods (undifferenced) while this is not the number of periods used in FD estimation.

**Comment by jepusto** [comment]
Yes, but see the following two lines, which drop the initial period from each group
```
index <- attr(model.frame(plm_FD), "index")
cluster <- index[[2]]
cluster <- cluster[index[[2]] != levels(index[[2]])[1]]
```

**Comment by jepusto** [comment]
It is indeed a bug in `vcovG.plm`. With `model = "fd"` and `cluster = "time"`, the function is dropping the meat contribution for final time point.

Not sure this is worth reporting (or where I would send the bug report), since it's kind of nonsensical to cluster on time in an FD model.

**Comment by helix123** [comment]
Great finding. I dropped the code maintainer a line (see ?vcovHC.plm and DESCRIPTION of plm). He will look at it.

**Comment by tappek** [comment]
`plm` `vcovG.plm` is now fixed when `model = "fd"` and `cluster = "time"` (in the development repository - commit 2ab514bf165cca22d886ee234f088e2ddca66d86)
