### ISSUE TITLE
nobs.plm can be removed as there is now  plm:::nobs.panelmodel on CRAN

### ISSUE THREAD

**Issue by helix123** [jepusto/clubSandwich#18]
Referring to (the beginning of) #13:
you can remove the `nobs.plm` method from clubSandwich for your next CRAN release (if you wish). There is now `plm:::nobs.panelmodel` in the latest CRAN release of `plm` (version 1.6-4) and you can rely on this if you want to (`nobs.panelmodel` also captures plm objects).

BTW: there is also support for clubSandwich's vcovs for `plm::pwaldtest` and hence one can pass a clubSandwich vcov in summary.plm and get identical results for the F statistic and partial wald tests on coefficients:

```
library(plm)
library(clubSandwich)
data(MortalityRates)

# partly from clubSandwich's vignette
# subset for deaths in motor vehicle accidents, 1970-1983
MV_deaths <- subset(MortalityRates, cause=="Motor Vehicle" & 
                      year <= 1983 & !is.na(beertaxa))

plm_unweighted <- plm(mrate ~ legal + beertaxa, data = MV_deaths, 
                      effect = "individual", index = c("state","year"))

vcov_club_id   <- vcovCR(plm_unweighted, type = "CR0", cluster = "individual")
vcov_plm_id    <- vcovHC(plm_unweighted, method="arellano", type="HC0", cluster = "group")

summary(plm_unweighted, vcov = vcov_plm_id) 
summary(plm_unweighted, vcov = vcov_club_id)
pwaldtest(plm_unweighted, test = "F", vcov = vcov_plm_id)
pwaldtest(plm_unweighted, test = "F", vcov = vcov_club_id)
```

**Comment by jepusto** [comment]
Thanks for the update! I would consider removing nobs.plm, but I think this would require that users have version >= 1.6-4 of plm. It might be better to wait a while before deprecating. (I've also checked that `clubSandwich:::nobs.plm()` is functionally identical to `plm:::nobs.panelmodel()`, so I think there's no harm in leaving it for now.)

**Comment by helix123** [comment]
Sure, it would require >= 1.6-4 of plm, so better wait a while.
