### ISSUE TITLE
"CR1S" Formula

### ISSUE THREAD

**Issue by wviechtb** [jepusto/clubSandwich#23]
According to the Stata documentation (Stata User's Guide, Release 13, section 20.21.2, 'Correlated errors: Cluster–robust standard errors'), the equation for "CR1S" should be `(m (N-1)) / [(m - 1)(N - p)]` (instead of `(m N) / [(m - 1)(N - p)]`).

**Comment by jepusto** [comment]
This was a mistake in the documentation only. The function itself is
consistent with the Stata documentation.
