### ISSUE TITLE
Two-way clustering for plm object?

### ISSUE THREAD

**Issue by yukitakahashi1** [jepusto/clubSandwich#37]
Hi! I'm trying to do two-way clustering with vcovCR() command after running fixed effects model with plm() by vcovCR(plm_FE,type="CR2",cluster=c("data$id","data$year")), but it returns the same covariance matrix estimate as one-way clustering. Is this covariance matrix estimate correct, or something is wrong with the syntax?

Sample code (adapted from the vcovCR.plm() help menu code):
library(plm)
data("Produc", package = "plm")
plm_FE <- plm(log(gsp) ~ log(pcap) + log(pc) + log(emp) + unemp, 
              data = Produc, index = c("state","year"), 
              effect = "individual", model = "within")  
vcovCR(plm_FE, type="CR2") % one-way clustering
vcovCR(plm_FE, type="CR2",cluster = c(Produc$state)) % same as above - one-way clustering
vcovCR(plm_FE, type="CR2",cluster = c(Produc$state,Produc$year)) % supposed to be two-way clustering, but returns the same covariance matrix as one-way clustering

**Comment by jepusto** [comment]
clubSandwich does not currently support two-way clustering. How to do the
small-sample adjustments for multi-way clustering is an open problem.

**Comment by yukitakahashi1** [comment]
Thank you very much James! I see - hope to see multiway clustering option in a near future. 
Sincerely,
Yuki

**Comment by helix123** [comment]
>  How to do the small-sample adjustments for multi-way clustering is an open problem.

I would have thought so but never found a reference in the literature about this being an open problem. Maybe you are aware of such a reference?

**Comment by jepusto** [comment]
MacKinnon & Webb are working on it, extending their wild bootstrapping techniques to models with cross-classification: https://www.econ.queensu.ca/sites/econ.queensu.ca/files/files/qed_wp_1415.pdf

**Comment by jepusto** [comment]
And we mentioned something about the issue in the discussion of our paper on CR2 for fixed effect models: https://www.jepusto.com/publication/rve-in-fixed-effects-models/
