### ISSUE TITLE
Specifying cluster variable sometimes fail

### ISSUE THREAD

**Issue by yukitakahashi1** [jepusto/clubSandwich#38]
Hi all!
I'm trying to specify a cluster variable after plm for my simulated data (which I use for power simulation), but I get the following error message:
"Error in `[.data.frame`(eval(mf$data, envir), , index_names) : undefined columns selected"

I'm not sure if this is specific to vcovCR or something general about R, but could anyone tell me what's wrong with my code?
My example (data file is in the attached zip file):
library(clubSandwich)
library(plm)
load("Data.RData")
fe.fit <- plm(formula = Y ~ T, data = Data, model = "within", index = "id",effect = "individual", singular.ok = FALSE)
vcovCR(fe.fit,cluster=Data$id,type = "CR2") # doesn't work, but I can run this by not specifying cluster as in the next line
vcovCR(fe.fit,type = "CR2")
vcovCR(fe.fit,cluster=Data$gid,type = "CR2") # I ultimately want to run this

For some other datasets, for example Produc in plm package, this works:
library(clubSandwich)
library(plm)
data("Produc", package = "plm")
plm_FE <- plm(log(gsp) ~ log(pcap) + log(pc) + log(emp) + unemp,
data = Produc, index = c("state","year"),
effect = "individual", model = "within")
vcovCR(plm_FE, type="CR2",cluster = Produc$state)

Thanks a lot!
[Data.zip](https://github.com/jepusto/clubSandwich/files/3101313/Data.zip)

**Comment by yukitakahashi1** [comment]
Ps. Let me post a revised code so that you don't have to download the data:
N <- 100;id <- 1:N;id <- c(id,id);gid <- 1:(N/2);
gid <- c(gid,gid,gid,gid);T <- rep(0,N);T = c(T,T+1)
a <- qnorm(runif(N),mean=0,sd=0.005)
gp <- qnorm(runif(N/2),mean=0,sd=0.0005)
u <- qnorm(runif(N*2),mean=0,sd=0.05)
a <- c(a,a);gp = c(gp,gp,gp,gp)
Ylatent <- -0.05*T + a + u
Data <- data.frame(
  Y = ifelse(Ylatent > 0, 1, 0),
  id = id,gid = gid,T = T
)
library(clubSandwich)
library(plm)
fe.fit <- plm(formula = Y ~ T, data = Data, model = "within", index = "id",effect = "individual", singular.ok = FALSE)
vcovCR(fe.fit,cluster=Data$id,type = "CR2") # doesn't work, but I can run this by not specifying cluster as in the next line
vcovCR(fe.fit,type = "CR2")
vcovCR(fe.fit,cluster=Data$gid,type = "CR2") # I ultimately want to run this

**Comment by helix123** [comment]
Your example does not work due to a bug in clubSandwich's data extraction function `get_index_order` (from version 0.3.3) for plm objects. It assumes both index variables are in the original data but this is not the case in your example where the time index is created automatically by only specifying the individual dimension by the index argument.

I suggest to simplify `get_index_order` to:

```
get_index_order <- function(obj) {
  index_names <- attr(model.frame(obj), "index")
  order(index[,1],index[,2])
}
```

**Comment by yukitakahashi1** [comment]
Thanks a lot @helix123! Also thanks for your answer to my Stackoverflow question; for reference to other people: https://stackoverflow.com/questions/55934280/how-to-cluster-standard-error-in-clubsandwichs-vcovcr. Yes, it worked by converting the data into a `pdata.frame`. @jepusto, it's nice if you could fix this, so that it's more straightforward to use this package.

**Comment by jepusto** [comment]
@yukitakahashi1, thanks very much for pointing out this issue and for providing a nice reproducible example. @helix123 thank you for your suggestion about how to fix it. What you've suggested isn't quite what I need though. `get_index_order` needs obtain the indexing variables in the order that they appeared in the original dataset. If the original dataset is not already sorted by the individual and time indices, `attr(model.frame(obj), "index")` will not agree with the indices from the original data.
