### ISSUE TITLE
multiple correction

### ISSUE THREAD

**Issue by meghapsimatrix** [jepusto/clubSandwich#48]
Can you adjust the p-value for multiple correction? That way you can have the symbols for the standard alpha values without having to mess with correcting alpha. Like what [p.adjust()](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/p.adjust.html) does.

Example:

if (mc_method == "Bonferroni"){
  
  res$p_val <- res$p_val * q   # q being number of contrasts
  res$sig <- symnum(x$p_val, corr = FALSE, na = FALSE, 
                    cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1), 
                    symbols = c("***", "**", "*", ".", " "))
  
  
}

**Comment by jepusto** [comment]
Redundant with #33.
