### ISSUE TITLE
clubSandwich moved to archive on CRAN

### ISSUE THREAD

**Issue by strengejacke** [jepusto/clubSandwich#50]
Hi, clubSandwich was recently removed from CRAN (https://cran.r-project.org/web/packages/clubSandwich/) - are there any plans to fix the issues and re-submit? I'm asking because one of my packages suggests clubSandwich, and I would have to remove it from the suggested packages if it will not come back to CRAN any time soon...

**Comment by jepusto** [comment]
Hi, yes I'm planning to fix the issues ASAP and re-submit. I just did a cross-country move so have been behind on correcting these issues.

**Comment by nch08a** [comment]
Is there a way to access an archive of the documentation?  I pulled the tar.gz from the CRAN page, but I'm not seeing the most recent documentation.

Thanks!

**Comment by jepusto** [comment]
Could you just install the current development version from Github? That should give you access to all of the man pages and vignettes.

**Comment by helix123** [comment]
Maintainers of packages with a dependency to clubSandwich received mails from CRAN that removal of their packages is soon (2020-09-09).

**Comment by jepusto** [comment]
I think I've resolved the issues and am just running all the checks in preparation for submission. However, I can't precisely replicate the configuration used for the MKL additional checks (which was the only one with an error in the previous submission), so not 100% sure. If anyone has access to a linux machine with R built against MKL, I'd be very grateful for any reports on package check results.

**Comment by helix123** [comment]
Sorry I cannot be helpful regards different BLAS implementations. I would have thought R-Hub could have various BLAS flavours but it is only planned upon an old suggestion of mine: https://github.com/r-hub/rhub/issues/275

**Comment by jepusto** [comment]
I just received notice from Uwe Ligges that the package is back on CRAN. Binaries should come available shortly, as usual.
