### ISSUE TITLE
problem indexing with coef_test()

### ISSUE THREAD

**Issue by bjvca** [jepusto/clubSandwich#80]
I used to extract coefficients etc using indexing, eg. coef_test(mod, vcov = S)[1,1]. But after migrating to a new laptop and upgrading, this gives me the variable name (constant) instead of the estimated coefficient. Is this intentional?

**Comment by jepusto** [comment]
﻿Yes. To make the output “tidy,” I have added variable names as the first column. I recommend indexing by name whenever possible, e.g. coef_test()$est[1].

**Comment by bjvca** [comment]
Tanks for your reply. I am sorry but coef_test()$est[1] returns NULL. How can I make sure this code does not break when people upgrade?

**Comment by jepusto** [comment]
Sorry, my initial reply had a mistake in it (that's what I get for responding from my phone). The variable is called `beta`, so `coef_test()$beta[1]` should return what you need. You can see the structure of the object by running
```
coef_test(obj, ...) |> str()
```

**Comment by bjvca** [comment]
Great, thank you, this is very helpful.
