### ISSUE TITLE
Robust SEs for ranef() and coef() from lme4/glmmTMB?

### ISSUE THREAD

**Issue by bwiernik** [jepusto/clubSandwich#82]
Would it be possible to add support for computing robust SEs for the estimated random effects or group-level total effects from lme4 and glmmTMB-type models?

**Comment by jepusto** [comment]
Is there theory to support this? I’m not aware of any work on this. Pointers appreciated.

**Comment by bwiernik** [comment]
I found some work in this area and am reading into it. Will check back in once I've got a clearer idea
