### ISSUE TITLE
Data error in vcov(gls())

### ISSUE THREAD

**Issue by MrJerryTAO** [jepusto/clubSandwich#90]
Hi @jepusto, 

I just tried your package with gls() models. Because I used dplyr when defining gls(..., data=), it caused errors in the get_data() method, as the data specified in $call of gls() is not a character name of any objects. A simple solution is that I assigned the data for modeling as an object with a simple name. You could try used eval() to regenerate the data from the gls()$call, so it is more generic and can take dplyr pipelines. 

```
clubSandwich:::get_data()
Error in exists(as.character(dat_name), envir = e) : 
  first argument has length > 1
```

**Comment by jepusto** [comment]
Thanks for the suggestion. I will take a look and consider it. Any chance you could provide a reproducible example to use for testing?

**Comment by MrJerryTAO** [comment]
Sure, see 

```
library(dplyr)
vcovCR(gls(mpg ~ hp, data = mtcars %>% filter())) # error in get_data
mydata <- mtcars %>% filter()
vcovCR(gls(mpg ~ hp, data = mydata)) # worked
model <- gls(mpg ~ hp, data = mtcars %>% filter())
model$data <- mtcars %>% filter()
vcovCR(model) # worked
```
