### ISSUE TITLE
Undocumented type = "CR4" argument

### ISSUE THREAD

**Issue by MrJerryTAO** [jepusto/clubSandwich#91]
Hi @jepusto, I noticed that vcovCR() allows type = "CR4", but there has been no documentation about what it does. The resulting SE and df look very similar to CR2. Is it a later and improved version of CR2 method? Is it better to use CR4 instead of CR2? 

The vcovCR.lme() and vcovCR.gls() methods essentially do the same thing, both leading to vcov_CR(), and there is a section in vcov_CR() `if (type %in% c("CR2", "CR4"))`.

**Comment by jepusto** [comment]
Yes, CR4 is currently an undocumented "Easter egg" in clubSandwich. I'm still working on understanding its properties and developing its implementation.
